import os
import time
import soundfile as sf
import onnxruntime as ort
from kokoro_onnx import Kokoro

# 1. Direct CUDA Provider without TensorRT search
os.environ["ONNX_PROVIDER"] = "CUDAExecutionProvider"

# Suppress verbose ONNX Runtime C++ logs
ort.set_default_logger_severity(3)

MODEL_PATH = "kokoro-v1.0.onnx"
VOICES_PATH = "voices-v1.0.bin"

print("Initializing Kokoro ONNX on NVIDIA RTX 3060 (CUDA)...")
t0 = time.perf_counter()
kokoro = Kokoro(MODEL_PATH, VOICES_PATH)
print(f"Model loaded in {(time.perf_counter() - t0) * 1000:.1f} ms")

# Available Hindi voices: 'hf_alpha', 'hf_beta', 'hm_omega', 'hm_psi'
# Available English voices for blending: 'af_heart', 'am_adam', etc.
voice_hindi = kokoro.get_voice_style("hf_alpha")
voice_english = kokoro.get_voice_style("af_heart")

# Blend voices: 70% Hindi cadence + 30% English clarity for natural Hinglish
blended_voice = (0.70 * voice_hindi) + (0.30 * voice_english)

# Typical output generated by LLM when prompted for Hinglish in Devanagari + English loan words
sample_text = (
    "नमस्ते! आपका server restart हो गया है। "
    "All processes normal हैं और system 100% stable काम कर रहा है।"
)

print(f"\nSynthesizing Hinglish:\n\"{sample_text}\"")

# Warm-up / Run
t1 = time.perf_counter()
samples, sample_rate = kokoro.create(
    sample_text,
    voice=blended_voice,
    speed=1.0,
    lang="hi"
)
gen_time = (time.perf_counter() - t1) * 1000
audio_duration = len(samples) / sample_rate

print(f"\nGeneration Completed!")
print(f"- Audio Duration : {audio_duration:.2f} seconds")
print(f"- Generation Time: {gen_time:.1f} ms")
print(f"- Real-time Speed: {audio_duration / (gen_time / 1000):.1f}x faster than real-time")

output_file = "hinglish_sample.wav"
sf.write(output_file, samples, sample_rate)
print(f"- Saved audio to  : {output_file}")
