import os
import time
import soundfile as sf
from kokoro_onnx import Kokoro

# Force CUDAExecutionProvider
os.environ["ONNX_PROVIDER"] = "CUDAExecutionProvider"

MODEL_PATH = "kokoro-v1.0.fp16.onnx"
VOICES_PATH = "voices-v1.0.bin"

print("Loading Kokoro ONNX model on CUDA...")
t0 = time.perf_counter()
kokoro = Kokoro(MODEL_PATH, VOICES_PATH)
t_load = (time.perf_counter() - t0) * 1000
print(f"Model loaded in {t_load:.2f} ms")

voices = kokoro.get_voices()
print(f"Total voices loaded: {len(voices)}")
hindi_voices = [v for v in voices if v.startswith("h")]
print(f"Hindi voices found: {hindi_voices}")

# Test Devanagari Hindi text (as generated by LLM system prompt)
test_text = "नमस्ते! कोकोरो ओएनएनएक्स आपके आरटीएक्स 3060 जीपीयू पर बहुत तेज़ी से चल रहा है।"
voice_name = "hf_alpha" if "hf_alpha" in voices else (hindi_voices[0] if hindi_voices else voices[0])

print(f"\nSynthesizing with voice '{voice_name}'...")
print(f"Input text: {test_text}")

t1 = time.perf_counter()
samples, sample_rate = kokoro.create(
    test_text,
    voice=voice_name,
    speed=1.0,
    lang="hi"
)
t_gen = (time.perf_counter() - t1) * 1000

duration_s = len(samples) / sample_rate
rtf = (t_gen / 1000) / duration_s

print(f"Generated {duration_s:.2f}s of audio in {t_gen:.2f} ms!")
print(f"Real-Time Factor (RTF): {rtf:.4f} (lower is faster, <1.0 is real-time)")
print(f"Speed: {1.0 / rtf:.1f}x faster than real-time!")

output_file = "test_hindi_cuda.wav"
sf.write(output_file, samples, sample_rate)
print(f"Saved output to {output_file}")
